import { Component, EventEmitter, Inject, inject, Input, Output, output, TemplateRef, ViewChild } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import {
  getAllTeamLeads,
  getUserDetails,
} from '../../../services/user.service';
import { UserService } from '../../../services/user.service';
import { ActivatedRoute, Router } from '@angular/router';
import { MAT_DIALOG_DATA, MatDialog, MatDialogRef } from '@angular/material/dialog';

@Component({
  selector: 'app-form-component',
  standalone: false,
  templateUrl: './form-component.component.html',
  styleUrl: './form-component.component.css',
})
export class FormComponentComponent {
  modalForm!: FormGroup;
  inputData: any;
  allTeamLeads: getAllTeamLeads[] = [];
  @Output() cancelClicked = new EventEmitter<void>();
  @Output() sucessPage = new EventEmitter<void>();
  buttonText: string = '';
  showSuccess = false;
  @Input() EditMemberInputData:any;
  @Input() teamId:any;
  @Input() teamMemberId:any

  openSuccessDialog!: MatDialogRef<any>;

  @ViewChild('successChangeDialog') successChangeDialog!: TemplateRef<any>;



  isEditMember=false
  constructor(
    // @Inject(MAT_DIALOG_DATA) public data: any,
    // private dialogRef: MatDialogRef<FormComponentComponent>,
    private dialog: MatDialog,
    private fb: FormBuilder,
    private service: UserService,
    private activatedRoute: ActivatedRoute,
    private router: Router
  ) {}

  ngOnChanges() {
    if (this.EditMemberInputData &&this.teamId) {
      console.log(this.teamMemberId);
      console.log(this.teamId);
      this.handleOninit()
    }
  }
  // add this.EditMemberInputData as parameter for handleOninit 
  handleOninit( ) {
    let id = this.activatedRoute.snapshot.paramMap.get('memberId');
    
    console.log(this.activatedRoute.snapshot);
    console.log(this.EditMemberInputData)
  
   
    if (id) {
      console.log('populate Edit data');
      this.buttonText = 'Save Changes';
      this.isEditMember=true

      this.service.getUser(id).subscribe({
        next: (data) => {
          console.log(data);
          this.modalForm.patchValue(data);
        },
        error: (err) => {
          console.log(err);
        },
      });
    } else if(this.EditMemberInputData){
     
      this.buttonText = 'Save Changes';
      this.modalForm.patchValue(this.EditMemberInputData)
      // this.service.getUser(this.teamMemberId).subscribe({
      //   next: (data) => {
      //     console.log(data);
      //     this.modalForm.patchValue(data);
      //   },
      //   error: (err) => {
      //     console.log(err);
      //   },
      // });

    }
    
    else {
      this.buttonText = 'Save';
    }
  }

  // check if it is an edit or create form
  ngOnInit(): void {


    this.handleOninit()
     
    // get all team Leads for select options
    this.service.getAllTeamLeads().subscribe({
      next: (data) => {
        this.allTeamLeads = data;
      },
      error: (err) => {
        console.log(err);
      },
    });

   

    // this.inputData = this.data

    // if (this.inputData.id.length > 0){
    //   console.log(this.inputData.id)
    //   this.setEditData('zQg79yqBiGVW3p9lUFBYA3ZJ9Ym5XQ','ojjsnv2crXprjvARhohGA30DKhUuSI')
    // }

    this.modalForm = this.fb.group({
      firstName: ['', [Validators.required, Validators.minLength(3)]],
      lastName: ['', [Validators.required, Validators.minLength(3)]],
      email: ['', [Validators.required, Validators.email]],
      phoneNumber: ['', [Validators.required, Validators.pattern(/^0\d{9}$/)]],
      teamLeadUserId: [''],
      role: ['TEAM_MEMBER'],
      password: ['AutoGeneratedPassword@123'],
      staffId: ['', Validators.required],
      // staffId: ['', Validators.required],
    });
  }
  // setEditData(teamLeadId:any,memberID:any){
  //   this.service.getSpecificTeamMember(memberID,teamLeadId).subscribe({
  //     next: (data) => {
  //     this.modalForm.patchValue(data)
  //       console.log(this.modalForm.value)
  //       console.log('data suppose ot go here')
  //     }

  //   })
  // }
  onSubmit() {
    let id = this.activatedRoute.snapshot.paramMap.get('memberId');
    if (id) {
      console.log('Send Update Request');
      console.log(this.modalForm.value);
      this.service.updateUserProfile(id, this.modalForm.value).subscribe({
        next: (data) => {
          console.log(data);
          this.sucessPage.emit();
            // this.showSuccess = true;
            console.log(this.showSuccess)
            this.isEditMember=true
        },
        error: (err) => {
          console.log(err);
        },
      });
    } else if(this.EditMemberInputData){
      if(this.modalForm.valid){
        this.service.updateUserProfile(this.teamMemberId, this.modalForm.value).subscribe({
          next: (data) => {
            console.log(data);
            this.sucessPage.emit();
            this.showSuccess = true;
            console.log(this.showSuccess)
            this.isEditMember=true
            this.modalForm.reset();
          },
          error: (err) => {
            console.log(err);
          },
        });
      }
    }
    
    else {
      console.log('Send Create Request here');
      if (this.modalForm.valid) {
        this.service.addTeamMember(this.modalForm.value).subscribe({
          next: () => {
            console.log(this.modalForm.value);
            this.sucessPage.emit();
            this.showSuccess = true;
            this.modalForm.reset();
          },
          error: (err) => {
            console.log(err);
          },
        });
      }
    }
  }

  closeModal(){
    this.openSuccessDialog.close()
  }

  openSuccessChangeDialog() {
    this.openSuccessDialog = this.dialog.open(this.successChangeDialog,{
       width: '600px',
       
     });
   }

  onCancel() {
    // console.log('helo')
    // this.router.navigate(['/admin/dashboard'])
    this.cancelClicked.emit();
  }

  createAnotherUser() {
    this.showSuccess = false;
  }
}
