import { Component, OnInit, EventEmitter, Output, Input} from '@angular/core';
import { FormBuilder, FormControl, FormGroup, Validators } from '@angular/forms';
import {getAllTeamLeads, UserService} from '../../../services/user.service'
@Component({
  selector: 'app-create-team-member',
  standalone: false,
  templateUrl: './create-team-member.component.html',
  styleUrl: './create-team-member.component.css'
})
export class CreateTeamMemberComponent {

  isModalOpen = false;
  showSuccess = false;
  modalForm!: FormGroup;
  allTeamLeads: getAllTeamLeads[] = [];

  constructor(private fb: FormBuilder, private UserService:UserService) {}

  
  ngOnInit(): void {

    // get all team Leads for select options
    this.UserService.getAllTeamLeads().subscribe({
      next: (data) => {
        this.allTeamLeads = data;  
      },
      error: (err) => {
        console.log(err)
      }
    })



    this.modalForm = this.fb.group({
      firstName: ['', [Validators.required, Validators.minLength(3)]],
      lastName: ['', [Validators.required, Validators.minLength(3)]],
      email: ['', [Validators.required, Validators.email]],
      phoneNumber: ['', [Validators.required, Validators.pattern(/^0\d{9}$/)]],
      teamLeadUserId: ['',Validators.required],
      role:['TEAM_MEMBER'],
      password:['AutoGeneratedPassword@123'],
      staffId: ['', Validators.required],
      // staffId: ['', Validators.required],
    });
  }

  onSubmit(): void {
    // this.showSuccess = true;
    console.log(this.modalForm.value)
    if(this.modalForm.valid){
      
      this.UserService.addTeamMember(this.modalForm.value).subscribe({
        next: ()=>{
          console.log(this.modalForm.value)
          this.showSuccess = true;
        },
        error: (err) => {
          console.log(err)
        }
      })

    }
  
}

@Output() onCancel = new EventEmitter<void>();

cancel(){
  this.onCancel.emit();
}

onSaveChanges(): void {
  if (this.modalForm.valid) {
    this.modalForm.reset()
  }
  this.showSuccess=false
  
}
}
