import { Component, EventEmitter, Inject, Optional, output, Output, TemplateRef, ViewChild } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { UserService } from '../../../services/user.service';
import { Router, ActivatedRoute } from '@angular/router';
import{MatDialogRef,MatDialog, MAT_DIALOG_DATA} from '@angular/material/dialog'
import { FormComponentComponent } from '../form-component/form-component.component';

@Component({
  selector: 'app-team-lead-form',
  standalone: false,
  templateUrl: './team-lead-form.component.html',
  styleUrl: './team-lead-form.component.css',
})
export class TeamLeadFormComponent {
  router: any;
  submitForm: any;
  @Output() removePopupTitle = new EventEmitter<void>();
  @Output() updateChanges = new EventEmitter<void>();

  isModalOpen = false;
  showSuccess = false;

  openSuccessDialog!: MatDialogRef<any>;

  startDate=""
  endDate=""

  allTeams:any

  teamFilter=""

  isEditMode=false;

  filterDuration=""

  @ViewChild('successChangeDialog') successChangeDialog!: TemplateRef<any>;

  constructor(
   @Optional() @Inject(MAT_DIALOG_DATA) public data: any,
    private dialogRef: MatDialogRef<FormComponentComponent>,
    private dialog: MatDialog,
    private fb: FormBuilder,
    private route: Router,
    private activatedRoute: ActivatedRoute,
    private userService: UserService
  ) {}

  createTeamLeadForm!: FormGroup;
  ngOnInit(): void {

    this.fetchAllTeams()

    console.log(this.activatedRoute.snapshot.paramMap);
    const id = this.activatedRoute.snapshot.paramMap.get('teamLeadId');

   
    this.createTeamLeadForm = this.fb.group({
      firstName: ['', [Validators.required, Validators.minLength(3)]],
      lastName: ['', [Validators.required, Validators.minLength(3)]],
      email: ['', [Validators.required, Validators.email]],
      phoneNumber: ['', [Validators.required, Validators.pattern(/^0\d{9}$/)]],
      staffId: ['', Validators.required],
      role: ['TEAM_LEAD'],
      password: ['AutoGeneratedPassword@123'],
      teamName: ['', Validators.required],
    });


    if (id) {
      this.isEditMode=true
      console.log('populate form fields with data');
      this.userService.getSpecificTeamLead(id, this.startDate, this.endDate,"").subscribe({
        next: (data) => {
          console.log(data);
          this.createTeamLeadForm.patchValue(data);
        },
        error: (err) => {
          console.log(err);
        },
      })
    }else if(this.data?.teamName){
      this.createTeamLeadForm.get('teamName')?.setValue(this.data.teamName)
      console.log(this.data.teamName)
    }

  }

  fetchAllTeams(){
    this.userService.getAllTeams("",this.teamFilter).subscribe({
      next: (data) => {
        this.allTeams = data;
        console.log(this.allTeams)
      },
      error: (err) => {
        console.log(err);
      },
    })
  }

  onSubmit(): void {
    const id = this.activatedRoute.snapshot.paramMap.get('teamLeadId');
    if (id) {
      console.log('send update request');
      this.userService.updateUserProfile(id, this.createTeamLeadForm.value).subscribe({
        next: (data) => {
          this.updateChanges.emit();
          console.log(data);
        },
        error: (err) => {
          console.log(err);
        },
      })
    } else {
      console.log('send create request');

      if (this.createTeamLeadForm.valid) {
        console.log(this.createTeamLeadForm.value);

        this.userService.addTeamLead(this.createTeamLeadForm.value).subscribe({
          next: (data) => {
            this.removePopupTitle.emit();
            this.showSuccess = true;
          },
          error: (err) => {
            console.log(err);
          },
        });
      }
    }
  }

  @Output() onCancel = new EventEmitter<void>();

  cancel() {
    this.onCancel.emit();
  }

  closeModal(){
    this.openSuccessDialog.close()
  }
  onSaveChanges(): void {
    if (this.createTeamLeadForm.valid) {
      this.createTeamLeadForm.reset();
    }
    this.showSuccess = false;
  }

  openSuccessChangeDialog() {
   this.openSuccessDialog = this.dialog.open(this.successChangeDialog,{
      width: '600px',
      
    });
  }
}
