import { Component, EventEmitter, Inject, inject, Input, Output, output, TemplateRef, ViewChild } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import {
  getAllTeamLeads,
  getUserDetails,
} from '../../../services/user.service';
import { UserService } from '../../../services/user.service';
import { ActivatedRoute, Router } from '@angular/router';
import { MAT_DIALOG_DATA, MatDialog, MatDialogRef } from '@angular/material/dialog';


@Component({
  selector: 'app-add-edit-member',
  standalone: false,
  templateUrl: './add-edit-member.component.html',
  styleUrl: './add-edit-member.component.css'
})
export class AddEditMemberComponent {

  modalForm!: FormGroup;
  inputData: any;
  allTeamLeads: getAllTeamLeads[] = [];
  
  showSuccess =false

  openSuccessDialog!: MatDialogRef<any>;

  @ViewChild('successChangeDialog') successChangeDialog!: TemplateRef<any>;

  page=0

  limit=20

  allTeams:any
  teamFilter=""

  memberId:any
  leadId:any

  isEditUser=false
  disableTeamField = false

  errorMessage="oops something went wrong"
  @Output() userCreated =new EventEmitter<any>()
  showError=false
  constructor(
    @Inject(MAT_DIALOG_DATA) 
    public data: any,
    private dialog: MatDialog,
    private fb: FormBuilder,
    private service: UserService,
    private activatedRoute: ActivatedRoute,
    private router: Router
  ) {}

  
  
  // check if it is an edit or create form
  ngOnInit(): void {
    console.log(this.data.teamName)


    this.modalForm = this.fb.group({
      firstName: ['', [Validators.required, Validators.minLength(3)]],
      lastName: ['', [Validators.required, Validators.minLength(3)]],
      email: ['', [Validators.required, Validators.email]],
      phoneNumber: ['', [Validators.required, Validators.pattern(/^0\d{9}$/)]],
      teamName: ['',Validators.required],
      role: ['',Validators.required],
      password: ['AutoGeneratedPassword@123'],
      staffId: ['', Validators.required],
      // staffId: ['', Validators.required],
    });
    this.fetchAllTeams()
    this.handleOnInit()
  }

 fetchAllTeams(){
  this.service.getAllTeams("",this.teamFilter).subscribe({
      next: (data) => {
        console.log(data)
        this.allTeams=data
      },
      error: (err) => {
        console.log(err);
      },
  })
 }

 handleOnInit(){
  this.memberId = this.activatedRoute.snapshot.paramMap.get('memberId');
  this.leadId = this.activatedRoute.snapshot.paramMap.get('teamLeadId');
  console.log(this.activatedRoute.snapshot);

  

  if(this.data.teamName){
    this.modalForm.get('teamName')?.setValue(this.data.teamName)
    this.disableTeamField=true
    // this.isEditUser=true
  
  }else if(this.data.memberId){
    this.isEditUser=true
    this.service.getUser(this.data.memberId).subscribe({
      next: (data) => {
        
        console.log(data);
        this.modalForm.patchValue(data);
      },
      error: (err) => {
        console.log(err);
      },
    })
  }
  console.log(this.activatedRoute.snapshot.paramMap);
 }
  




  
  onSubmit() {

    if(this.data.memberId){
    
      this.service.updateUserProfile(this.data.memberId, this.modalForm.value).subscribe({
        next: (data) => {
          console.log(data);
         
          
        },
        error: (err) => {
          console.log(err);
          this.showError=true
        },
      })
    }else{
      console.log(this.modalForm.value)
     

      this.service.addTeamLead(this.modalForm.value).subscribe({
        next: (data) => {
          console.log(data);
          this.showSuccess=true
          this.userCreated.emit()
        },
        error: (err) => {
          console.log(err);
          this.showError=true
        },
      });
    }
  }

  // onCancel() {
  //   this.cancelClicked.emit();
  // }

  createAnotherUser() {
    this.modalForm.reset();
    this.showSuccess = false;
  }

  openSuccessChangeDialog() {
    this.openSuccessDialog = this.dialog.open(this.successChangeDialog,{
       width: '600px',
       
     });
   }

   refreshPage(){
    window.location.reload()
  }

  }



