import { Component, OnInit, EventEmitter, Output, Input} from '@angular/core';
import { FormBuilder, FormControl, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { Inject } from '@angular/core';
import {UserService,createTeamLead} from '../../services/user.service'

@Component({
  selector: 'app-dialog',
  templateUrl: './create-team-lead.component.html',
  styleUrls: ['./create-team-lead.component.css'],
  standalone: false,
})
export class CreateTeamLeadComponent  {


  router: any;
  submitForm: any;



  isModalOpen = false;
  showSuccess = false;

  constructor(private fb: FormBuilder, private userService: UserService) {}

  createTeamLeadForm!: FormGroup;
  ngOnInit(): void {
    this.createTeamLeadForm = this.fb.group({
      firstName: ['', [Validators.required, Validators.minLength(3)]],
      lastName: ['', [Validators.required, Validators.minLength(3)]],
      email: ['', [Validators.required, Validators.email]],
      phoneNumber: ['', [Validators.required, Validators.pattern(/^0\d{9}$/)]],
      staffId: ['', Validators.required],
      role: ['TEAM_LEAD'],
      password: ['AutoGeneratedPassword@123'],
    });
  }



    onSubmit(): void {
    
      
      console.log(this.createTeamLeadForm.value)
      this.userService.addTeamLead(this.createTeamLeadForm.value).subscribe({
        next: (data) => {
          this.showSuccess = true;  
        },
        error:(err)=> {
          console.log(err)
        }
      })
      
   
  
}

@Output() onCancel = new EventEmitter<void>();

cancel(){
  this.onCancel.emit();
}




  onSaveChanges(): void {
    if (this.createTeamLeadForm.valid) {
      this.createTeamLeadForm.reset()
    }
    this.showSuccess=false
    
  }

}

